
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
#    org.springframework.boot.autoconfigure: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true

  health:
    livenessState: # ?? /actuator/health/liveness
      enabled: true
    readinessState: # ?? /actuator/health/readiness
      enabled: true

  metrics:
    enable:
      jvm: true
    use-global-registry: false
    tags:
      application: ${spring.application.name}


server:
  shutdown: graceful
  port: 8010

spring:
  docker:
    compose:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: local
  application:
    name: example-spring-security-multiple-authentication

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.oauth2.domain}/oauth2/jwks
      client:
        registration:
          example-spring-authorization-server:
            provider: example-spring-authorization-server
            client-id: example-spring-security-multiple-authentication
            client-name: example-spring-security-multiple-authentication
            client-secret: example-spring-security-multiple-authentication-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - read
              - write
              - profile
              - email
              - address
              - phone
        provider:
          example-spring-authorization-server:
            jwk-set-uri: ${app.oauth2.domain}/oauth2/jwks
            authorization-uri: ${app.oauth2.domain}/oauth2/authorize
            token-uri: ${app.oauth2.domain}/oauth2/token
            user-info-uri: ${app.oauth2.domain}/userinfo
            user-name-attribute: sub


app:
  oauth2:
    domain: http://example-spring-authorization-server.local:9000
