
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
#    org.springframework.boot.autoconfigure: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true

  health:
    livenessState: # ?? /actuator/health/liveness
      enabled: true
    readinessState: # ?? /actuator/health/readiness
      enabled: true

  metrics:
    enable:
      jvm: true
    use-global-registry: false
    tags:
      application: ${spring.application.name}


server:
  shutdown: graceful
  port: 8010

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: local
  application:
    name: example-spring-security-multiple-authentication

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          toquery-example:
            client-id: example
            client-name: example
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/admin/index
            provider: toquery-example-provider
            scope:
              - openid
              - write
              - read
        provider:
          toquery-example-provider:
            jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
            authorization-uri: http://127.0.0.1:9000/oauth2/authorize
            token-uri: http://127.0.0.1:9000/oauth2/token
