### OAuth2 Authenticate
POST http://localhost:9000/filter/login
Content-Type: application/json

{
  "username":"filter",
  "password":"123456"
}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Query Info Endpoint
# @no-cookie-jar
GET http://localhost:8010/filter/info
Authorization: Bearer {{access_token}}
